version: '3.9'
services:
  app:
    container_name: app
    build: .
    command: npm run ${ENV}
    ports:
     - 5000:4002
    depends_on:
      - db
    volumes:
     - .:/usr/src/app
  db:
    image: postgres:14
    container_name: db
    hostname: ${POSTGRES_HOST}
    ports:
      - 2345:${POSTGRES_PORT}
    restart: always
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
